name: Configure AWS Credentials

on: [workflow_dispatch, pull_request]
  
# permission can be added at job level or workflow level
permissions:
  id-token: write  
  contents: read
jobs:
  run_job_with_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::890742561478:role/github-oidc
          aws-region: eu-west-2
          role-session-name: ghawsoidc  # session name, requires GH to use the name "ghawsoidc" If it tries to use any other name,
          # AWS will block the login.