name: AWS example workflow

on:
  workflow_dispatch
  
# permission can be added at job level or workflow level
permissions:
  id-token: write  
  contents: read
jobs:
  run_job_with_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::890742561478
          aws-region: eu-west-2
    #   - name: Additional steps
    #     run: |
    #       # Your commands that require AWS credentials
    #       aws sts get-caller-identity
