name: Terraform Destroy
on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "DESTROY" to confirm'
        required: true
        type: string

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
                terraform_version: "1.14.3"
                cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
        

      - name: Terraform Destroy
        # Only runs if the user typed the exact confirmation string
        if: github.event.inputs.confirm_destroy == 'DESTROY'
        run: terraform destroy -auto-approve -input=false
