name: AWS-Terraform-Apply
run-name: aws-terraform-apply

on: 
  pull_request:
    types:
      - closed
    branches:
      - 'main'
  
# permissions to be granted for workflow 
permissions: #generates tokens for each job on the workflow
  id-token: write  
  contents: read
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    # environment:
    #   name: 'aws-main-environment'
    steps:
    - run: |
        echo The PR was merged

  terraform-apply:
    runs-on: ubuntu-latest
    defaults:
        run: 
          shell: bash 
          working-directory: ./terraform
  
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::890742561478:role/github-oidc-test
          aws-region: eu-west-2
          role-session-name: ghawsoidc-test  # session name, requires GH to use the name "ghawsoidc-test" If it tries to use any other name,
          # AWS will block the login.
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v4
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Apply
        id: plan
        run: terraform apply -auto-approve -state-out=path
        continue-on-error: true    